######################################################################
#
# File name : main_simulate.do
# Created on: Tue Nov 19 14:38:50 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xpm -L dist_mem_gen_v8_0_13 -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.main xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {main_wave.do}

view wave
view structure
view signals

do {main.udo}

run 1000ns
