######################################################################
#
# File name : main_wave.do
# Created on: Tue Nov 19 14:38:50 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
