######################################################################
#
# File name : main_tb.udo
# Created on: Tue Nov 19 14:40:18 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
