######################################################################
#
# File name : main_tb_compile.do
# Created on: Thu Nov 21 17:56:42 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/dist_mem_gen_v8_0_13
vlib modelsim_lib/msim/xil_defaultlib

vmap dist_mem_gen_v8_0_13 modelsim_lib/msim/dist_mem_gen_v8_0_13
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work dist_mem_gen_v8_0_13  \
"../../../../project_8.ip_user_files/ipstatic/simulation/dist_mem_gen_v8_0.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../../../project_8.srcs/sources_1/ip/dist_mem_gen_0/sim/dist_mem_gen_0.v" \
"../../../../project_8.srcs/sources_1/new/F_CODE.v" \
"../../../../project_8.srcs/sources_1/new/SPKER.v" \
"../../../../project_8.srcs/sources_1/new/main.v" \
"../../../../project_8.srcs/sim_1/new/main_tb.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

