######################################################################
#
# File name : main_compile.do
# Created on: Tue Nov 19 14:38:42 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/dist_mem_gen_v8_0_13

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap xpm modelsim_lib/msim/xpm
vmap dist_mem_gen_v8_0_13 modelsim_lib/msim/dist_mem_gen_v8_0_13

vlog -64 -incr -sv -work xil_defaultlib  \
"C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -64 -93 -work xpm  \
"C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -64 -incr -work xil_defaultlib  \
"../../../../project_8.srcs/sources_1/ip/ila_0/sim/ila_0.v" \

vlog -64 -incr -work dist_mem_gen_v8_0_13  \
"../../../../project_8.ip_user_files/ipstatic/simulation/dist_mem_gen_v8_0.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../../../project_8.srcs/sources_1/ip/dist_mem_gen_0/sim/dist_mem_gen_0.v" \
"../../../../project_8.srcs/sources_1/new/CNT138T.v" \
"../../../../project_8.srcs/sources_1/new/FDTV.v" \
"../../../../project_8.srcs/sources_1/new/F_CODE.v" \
"../../../../project_8.srcs/sources_1/new/SPKER.v" \
"../../../../project_8.srcs/sources_1/new/main.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

