######################################################################
#
# File name : a1_compile.do
# Created on: Tue Oct 08 20:17:24 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../project_1.srcs/sources_1/new/a1.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

