######################################################################
#
# File name : a1_simulate.do
# Created on: Tue Oct 08 20:17:26 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.a1 xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {a1_wave.do}

view wave
view structure
view signals

do {a1.udo}

run 1000ns
