######################################################################
#
# File name : a1_wave.do
# Created on: Tue Oct 08 19:05:10 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
