######################################################################
#
# File name : pc_tb_wave.do
# Created on: Tue Nov 26 20:21:44 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
