######################################################################
#
# File name : cnt10_wave.do
# Created on: Tue Oct 22 18:54:40 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
