######################################################################
#
# File name : cnt10_tb_wave.do
# Created on: Tue Oct 22 18:59:07 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
