######################################################################
#
# File name : cnt10_compile.do
# Created on: Tue Oct 22 18:54:36 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../project_3.srcs/sources_1/new/cnt10.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

