######################################################################
#
# File name : vga_tb.udo
# Created on: Tue Nov 05 19:11:19 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
