######################################################################
#
# File name : schk_tb_wave.do
# Created on: Tue Nov 12 19:40:33 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
