######################################################################
#
# File name : vga_tb_wave.do
# Created on: Tue Nov 05 19:17:55 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
