######################################################################
#
# File name : cnt10_tb_simulate.do
# Created on: Tue Oct 22 19:33:01 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.cnt10_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {cnt10_tb_wave.do}

view wave
view structure
view signals

do {cnt10_tb.udo}

run 1000ns
