######################################################################
#
# File name : alu_tb_wave.do
# Created on: Tue Oct 15 18:59:27 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
