######################################################################
#
# File name : alu_tb_simulate.do
# Created on: Tue Oct 15 19:29:10 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.alu_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {alu_tb_wave.do}

view wave
view structure
view signals

do {alu_tb.udo}

run 1000ns
