######################################################################
#
# File name : alu_tb_compile.do
# Created on: Tue Dec 10 17:17:42 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../project_2.srcs/sources_1/new/alu.v" \
"../../../../project_2.srcs/sim_1/new/alu_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

