set_property SRC_FILE_INFO {cfile:C:/Users/YangZhen/Documents/VivadoProject/project_1/project_1.srcs/constrs_2/new/a1.xdc rfile:../../../project_1.srcs/constrs_2/new/a1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports {a[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports {a[1]}]
